version: '3'
services:
   backend:
      build: backend
      restart: always
      ports:
         - "8081:8081"
      depends_on:
         - db
         - rabbitmq
      environment:
         SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rtuit_backend
         SPRING_DATASOURCE_USERNAME: postgres
         SPRING_DATASOURCE_PASSWORD: postgres
         SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
         SPRING_RABBITMQ_HOST: rabbitmq
         SPRING_RABBITMQ_PORT: 5672
         SPRING_RABBITMQ_USERNAME: guest
         SPRING_RABBITMQ_PASSWORD: guest
   
   notification:
      build: notification
      restart: always
      ports:
         - "8082:8082"
      depends_on:
         - backend
      environment:
         SPRING_RABBITMQ_HOST: rabbitmq
         SPRING_RABBITMQ_PORT: 5672
         SPRING_RABBITMQ_USERNAME: guest
         SPRING_RABBITMQ_PASSWORD: guest

   rabbitmq:
      image: rabbitmq:3-management
      restart: always
      ports:
         - "5672:5672"
         - "15672:15672"
      environment:
         RABBITMQ_DEFAULT_USER: guest
         RABBITMQ_DEFAULT_PASS: guest
   
   db:
      image: postgres
      restart: always
      ports:
         - "5432:5432"
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         POSTGRES_DB: rtuit_backend
         
   adminer:
      image: adminer
      restart: always
      ports:
         - "8080:8080"
      depends_on:
         - db