spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rtuit_backend
    username: zakat
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /api/docs/ui.html
  api-docs:
    path: /api/docs

app:
  jwt:
    secret-key: 645367556B58703273357638792F423F4528482B4D6251655468576D59713374
    expiration:
      time-amount: 2
      time-unit: DAYS